import type { Metadata } from 'next'
import Navbar from '@/components/navbar/Navbar'
import '@/styles/globals.scss'

export const metadata: Metadata = {
  title: 'PN Movie',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        {children}
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
      </body>
    </html>
  )
}
